# Generated by Django 5.0.4 on 2024-05-09 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_session_id'),
        ('checkout', '0007_order_shipping_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='checkout_or_user_id_6a73f6_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'cart', 'shipping_address', 'billing_type', 'email', 'active'], name='checkout_or_user_id_df3b1f_idx'),
        ),
    ]
