# Generated by Django 5.0.4 on 2024-05-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='nickname',
        ),
    ]
