# Generated by Django 5.0.4 on 2024-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('deliveried', 'deliveried'), ('pending', 'pending')], default='cash_on_delivery', max_length=120, null=True),
        ),
    ]
