# Generated by Django 5.0.4 on 2024-05-01 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_description_product_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('', 'Choose Product Unit'), ('kg', 'kg'), ('l', 'litre'), ('pcs', 'pcs'), ('gm', 'gm'), ('m2', 'm2'), ('m3', 'm3'), ('ml', 'ml')], default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'store', 'active', 'featured', 'unit', 'slug', 'created_at'], name='products_pr_title_c8aec9_idx'),
        ),
    ]
