# Generated by Django 5.0.4 on 2024-05-01 08:17

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_title_c8aec9_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='products', to='products.category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'store', 'active', 'featured', 'price', 'unit', 'cost', 'quantity', 'descriptions', 'is_digital', 'slug', 'created_at', 'category'], name='products_pr_title_46da8a_idx'),
        ),
    ]
