# Generated by Django 5.0.4 on 2024-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(default='Agro Farm', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='health_check',
            field=models.CharField(default='Healthy', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='min_weight',
            field=models.CharField(default='250 gm', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.CharField(default='Organic', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='1 kg', max_length=50),
        ),
    ]
