# Generated by Django 5.0.4 on 2024-05-06 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_country_of_origin_product_health_check_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['weight'], name='products_pr_weight_250faa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['country_of_origin'], name='products_pr_country_163b79_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['quality'], name='products_pr_quality_e91a12_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['health_check'], name='products_pr_health__1e9fea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['min_weight'], name='products_pr_min_wei_d94b6b_idx'),
        ),
    ]
