# Generated by Django 5.0.4 on 2024-05-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
