# Generated by Django 5.0.4 on 2024-05-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_contact'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='users_custo_email_4079f2_idx',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='permenet', max_length=20, verbose_name='Gender'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email', 'username', 'bio', 'source', 'contact', 'full_name', 'country', 'gender', 'nationality', 'user_type'], name='users_custo_email_538b4b_idx'),
        ),
    ]
